model_configs:
  extract_product:
    model_name: gpt-4o-mini
    provider: openai
    prompt_file: prompt_templates/extract_product.json
    temperature: 0.0
  embedding:
    model_name: text-embedding-3-small,text-embedding-ada-002, text-embedding-3-large
    provider: openai
    vector_index: db/faiss_index
  recommend_recipes:
    model_name: gpt-4o-mini
    provider: openai
    prompt_file: prompt_templates/recommend_recipes.json
    temperature: 0.0

data_path:
    pdf: data/flyer.pdf
    recipe_books: data/recipes

output_path:
    images: outputs/extracted_images
    products: outputs/extracted_products
    recipes: outputs/recommended_recipes
