model_config:
  extract_product:
    model_name: llama-3.2-11b-vision-preview, llama-3.2-90b-vision-preview, llava-v1.5-7b-4096-preview
    provider: groq
    prompt_file: prompt_templates/extract_product.json
    temperature: 0.0
  embedding:
    model_name: text-embedding-ada-002
    provider: openai
    vector_index: db/faiss_index
  recommend_recipes:
    model_name: llama-3.1-70b-versatile
    provider: groq
    prompt_file: prompt_templates/recommend_recipes.json
    temperature: 0.0

data_path:
    pdf: data/flyer.pdf
    recipe_books: data/recipes

output_path:
    images: outputs/extracted_images
    products: outputs/extracted_products
    recipes: outputs/recommended_recipes
